### ISSUE TITLE
feature complete meta issue

### ISSUE THREAD

**Issue by cpdean** [cpdean/ug#1]
lifted from ag's usage:

- [ ] `--ackmate`            Print results in AckMate-parseable format
- [ ] `-A --after [LINES]`      Print lines after match (Default: 2)
- [ ] `-B --before [LINES]`     Print lines before match (Default: 2)
- [ ] `--[no]break`          Print newlines between matches in different files
- [ ] `-c --count`              Only print the number of matches in each file.
- [ ] `--[no]color`          Print color codes in results (Enabled by default)
- [ ] `--color-line-number`  Color codes for line numbers (Default: 1;33)
- [ ] `--color-match`        Color codes for result match numbers (Default: 30;43)
- [ ] `--color-path`         Color codes for path names (Default: 1;32)
- [ ] `--column`             Print column numbers in results
- [ ] `--[no]filename`       Print file names (Enabled unless searching a single file)
- [ ] `-H --[no]heading`        Print file names before each file's matches
- [ ] `-C --context [LINES]`    Print lines before and after matches (Default: 2)
- [ ] `--[no]group`          Same as --[no]break --[no]heading
- [ ] `-g PATTERN`              Print filenames matching PATTERN
- [ ] `-l --files-with-matches` Only print filenames that contain matches
- [ ] `-L --files-without-matches`
- [ ] `--[no]numbers`        Print line numbers. Default is to omit line numbers
- [ ] `-o --only-matching`      Prints only the matching part of the lines
- [ ] `--print-long-lines`   Print matches on very long lines (Default: >2k characters)
- [ ] `--passthrough`        When searching a stream, print all lines even if they
- [ ] `--silent`             Suppress all log messages, including errors
- [ ] `--stats`              Print stats (files scanned, time taken, etc.)
- [ ] `--vimgrep`            Print results like vim's :vimgrep /pattern/g would
- [ ] `-0 --null --print0`      Separate filenames with null (for 'xargs -0')
- [ ] `-a --all-types`          Search all files (doesn't include hidden files
- [ ] `-D --debug`              Ridiculous debugging (probably not useful)
- [ ] `--depth NUM`          Search up to NUM directories deep (Default: 25)
- [ ] `-f --follow`             Follow symlinks
- [ ] `-F --fixed-strings`      Alias for --literal for compatibility with grep
- [ ] `-G --file-search-regex`  PATTERN Limit search to filenames matching PATTERN
- [ ] `--hidden`             Search hidden files (obeys .*ignore files)
- [ ] `-i --ignore-case`        Match case insensitively
- [ ] `--ignore PATTERN`     Ignore files/directories matching PATTERN
- [ ] `--ignore-dir NAME`    Alias for --ignore for compatibility with ack.
- [ ] `-m --max-count NUM`      Skip the rest of a file after NUM matches (Default: 10,000)
- [ ] `--one-device`         Don't follow links to other devices.
- [ ] `-p --path-to-agignore STRING` Use .agignore file at STRING
- [ ] `-Q --literal`            Don't parse PATTERN as a regular expression
- [ ] `-s --case-sensitive`     Match case sensitively
- [ ] `-S --smart-case`         Match case insensitively unless PATTERN contains
- [ ] `--search-binary`      Search binary files for matches
- [ ] `-t --all-text`           Search all text files (doesn't include hidden files)
- [ ] `-u --unrestricted`       Search all files (ignore .agignore, .gitignore, etc.; searches binary and hidden files as well)
- [ ] `-U --skip-vcs-ignores`   Ignore VCS ignore files
- [ ] `-v --invert-match`
- [ ] `-w --word-regexp`        Only match whole words
- [ ] `-z --search-zip`         Search contents of compressed (e.g., gzip) files
